### ISSUE TITLE
How did you do that calendar?

### ISSUE THREAD

**Issue by abinlatheef** [donovanglover/dotfiles#3]
Can you please share that calendar script that is shown in the first screenshot?

**Comment by donovanglover** [comment]
It's [`calcurse`](https://calcurse.org/) with a small window.

**Comment by abinlatheef** [comment]
Oh Thanks.

**Comment by abinlatheef** [comment]
Oh is it just a window you open from terminal? I thought it would be some popup calendar when you click on the date on polybar like in gnome and all. My bad.
